/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook.glb -T
Files: macbook.glb [629.72KB] > /Users/adrianhajdin/Desktop/macbook_gsap_app/public/models/macbook-transformed.glb [627.9KB] (0%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import React, { useEffect, useRef, useState } from 'react';
import { useGLTF, useVideoTexture } from '@react-three/drei';
import useMacbookStore from "../../store/index.js";
import { noChangeParts, featureSequence } from "../../constants/index.js";
import { Color } from "three";

const VideoTexture = ({ src }) => {
  const texture = useVideoTexture(src, {
    start: true,
    unsuspend: 'canplay',
    crossOrigin: 'anonymous',
  });
  return <meshBasicMaterial map={texture} />;
};

export default function MacbookModel(props) {
  const { color, texture } = useMacbookStore();
  const { nodes, materials, scene } = useGLTF('/models/macbook-transformed.glb');
  const [loadedTextures, setLoadedTextures] = useState({});
  const loadingRef = useRef(false);

  // Preload all video textures
  useEffect(() => {
    if (loadingRef.current) return;
    loadingRef.current = true;

    const loadTextures = async () => {
      const textureMap = {};

      await Promise.all(
        featureSequence.map((feature) => {
          return new Promise((resolve) => {
            const video = document.createElement('video');
            video.src = feature.videoPath;
            video.muted = true;
            video.playsInline = true;
            video.preload = 'auto';
            video.crossOrigin = 'anonymous';
            video.load();

            video.oncanplay = () => {
              textureMap[feature.videoPath] = true;
              setLoadedTextures({ ...textureMap });
              resolve();
            };
          });
        })
      );
    };

    loadTextures();
  }, []);

  useEffect(() => {
    scene.traverse((child) => {
      if (child.isMesh) {
        if (!noChangeParts.includes(child.name)) {
          child.material.color = new Color(color);
        }
      }
    });
  }, [color, scene]);

  const isTextureLoaded = loadedTextures[texture];

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.zhGRTuGrQoJflBD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.lmWQsEjxpsebDlK} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.LtEafgAVRolQqRw} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.iyDJFXmHelnMTbD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.eJObPwhgFzvfaoZ} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.nDsMUuDKliqGFdU} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.CRQixVLpahJzhJc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.YYwBgwvcyZVOOAA} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.SLGkCohDDelqXBu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.WnHKXHhScfUbJQi} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.fNHiBfcxHUJCahl} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.LpqXZqhaGCeSzdu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.gMtYExgrEUqPfln} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.PaletteMaterial003} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.JvMFZolVCdpPqjj} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_123.geometry} rotation={[Math.PI / 2, 0, 0]}>
        {isTextureLoaded ? (
          <VideoTexture src={texture} />
        ) : (
          <meshBasicMaterial color="#000000" />
        )}
      </mesh>
      <mesh geometry={nodes.Object_127.geometry} material={materials.ZCDwChwkbBfITSW} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  );
}

useGLTF.preload('/models/macbook-transformed.glb');